[tool.poetry]
name = "album-challenge-40"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
discord = "^2.1.0"
pytz = "^2022.7.1"
pandas = "^1.5.3"
wordcloud = "^1.8.2"
bs4 = "^0.0.1"
discogs = "^0.2"
discogs-client = "^2.3.0"
Flask = "^2.2.3"
replit = "^3.2.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
